language: rust

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
      rust: nightly-2018-11-21-x86_64-unknown-linux-gnu

install:
  - rustup target add $TARGET

script:
  script:
  - cd narc_rust/app
  - cargo build --example fsm
  - cargo build --example blink
  - cargo build --example serial
  - cargo build --example led
  - cargo build --example systick
  - cargo build --example delay

