language: rust

matrix:
  include:
    - env: TARGET=thumbv6m-none-eabi
      rust: nightly-2019-01-09-x86_64-unknown-linux-gnu

install:
  - rustup target add $TARGET

script:
  - cd narc_rust/hal && cargo build
  - cd ../app && cargo build && cargo build --example fsm

